name: Release

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3

  build-push-image-update-container:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yc-actions/yc-sls-function@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: 'b1g2l27mgta22ibfjk5n'
          function-name: 'tg-bot-mm'
          runtime: 'golang121'
          memory: '128Mb'
          entrypoint: 'cmd/cloud-function/main.Handler'
          environment: |
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            DATABASE_TYPE=${{ vars.DATABASE_TYPE }}
            NOTIFICATION_CHAT_ID=${{ vars.NOTIFICATION_CHAT_ID }}
            PORT=${{ vars.PORT }}
            YDB_AUTH_FILE_DIR_NAME=${{ vars.YDB_AUTH_FILE_DIR_NAME }}
            YDB_AUTH_FILE_NAME=${{ vars.YDB_AUTH_FILE_NAME }}
            YDB_DSN=${{ vars.YDB_DSN }}
